services:
  api:
    image: fredsonchaves07/tools-challenge-pagamentos-api:${APP_VERSION}
    container_name: tools-challenge-pagamentos-api
    env_file:
      - .env
    environment:
      COMPOSE_REMOVE_ORPHANS: ${COMPOSE_REMOVE_ORPHANS:-true}
      COMPOSE_BAKE: ${COMPOSE_BAKE:-true}
      COMPOSE_FILE: ${COMPOSE_FILE:-compose.dev}
      APP_VERSION: ${APP_VERSION}
      APP_PORT: ${APP_PORT}
    restart: unless-stopped
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:17
    container_name: tools-challenge-pagamentos-database
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DB_USERNAME} -d ${DB_NAME}'" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./docker/init/database:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local